export const GET_USER_INFO = 'GET_USER_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';

export const GET_USER_CHATS_REQUEST = 'GET_USER_CHATS_REQUEST';
export const GET_USER_CHATS_SUCCESSS = 'GET_USER_CHATS_SUCCESSS';
export const GET_USER_CHATS_FAILURE = 'GET_USER_CHATS_FAILURE';

export const NEW_USER_INFO = 'NEW_USER_INFO';
export const NEW_USER_INFO_ERROR = 'NEW_USER_INFO_ERROR';
