export const GET_USER_INFO = 'GET_USER_INFO';
export const SET_USER_INFO = 'SET_USER_INFO';

export const GET_USER_CHATS_REQUEST = 'GET_USER_CHATS_REQUEST';
export const GET_USER_CHATS_SUCCESS = 'GET_USER_CHATS_SUCCESS';
export const GET_USER_CHATS_FAILURE = 'GET_USER_CHATS_FAILURE';

export const GET_CHATS_REQUEST = 'GET_CHATS_REQUEST';
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS';
export const GET_CHATS_FAILURE = 'GET_CHATS_FAILURE';

export const SET_SELECTED_CHAT = 'SET_SELECTED_CHAT';

export const NEW_USER_INFO = 'NEW_USER_INFO';
export const NEW_USER_INFO_ERROR = 'NEW_USER_INFO_ERROR';
